### ISSUE TITLE
Debugger timing out on Attach to Process...Mac OS

### ISSUE THREAD

**Issue by timnaylor** [cmcpasserby/MayaCharm#55] opened 2020-10-07 22:32 UTC
Hi - I am having difficulty getting PyCharm to connect with Maya via MayaCharm on the Mac. Here are the specs:

MacOS Mojave (10.14.6)

Maya 2019.2

PyCharm Professional 2019.2.6

MayaCharm 3.1.1

I have the correct python interpreter within the MayaCharm preferences set to:
/Applications/Autodesk/maya2019/Maya.app/Contents/bin/mayapy

I have updated my userSetup.py to include the following commands:
```
import maya.cmds as cmds

if not cmds.commandPort(':4434', query=True):
    cmds.commandPort(name=':4434')
```

When I use "Run -> Attach To Process" the following is executed:

Applications/Autodesk/maya2019/Maya.app/Contents/bin/mayapy /Applications/PyCharm.app/Contents/helpers/pydev/pydevd_attach_to_process/attach_pydevd.py --port 51087 --pid 26474

Process finished with exit code 0
Server stopped.

Then Maya hangs and I have to quit out of PyCharm. I've tried different port numbers (6001) thinking it might be some security restriction on Mojave but to no avail. 

Any help or ideas would be awesome!

Thanks,
Tim

**Comment by cmcpasserby** [comment] 2021-03-18 00:04
closing this for now since the way attaching to the Maya instance has changed a lot in the 3.2.x version of MayaCharm. Can reopen if it reproduceable in the new versions.

**Closed by cmcpasserby** 2021-03-18 00:04 UTC
