### ISSUE TITLE
File "<maya console>", line 1, in <module>  IOError: [Errno 2] No such file or directory: '' 

### ISSUE THREAD

**Issue by IonutStef** [cmcpasserby/MayaCharm#8] opened 2016-11-01 23:18 UTC
Hi! When I run the script, I receive this Error in both Maya and PyCharm...

**Comment by cmcpasserby** [comment] 2016-11-01 23:43
can you give me some more info about, what system you are running on and things like the maya pycharm and mayacharm versions.

**Comment by cmcpasserby** [comment] 2016-11-08 01:39
i believe you are the same person that post on the plugin repos page, so i will also leave my response here.
@ionutstef Hey, sorry you are having some problems. I have a very basic step by step, on github. https://github.com/cmcpasserby/MayaCharm/blob/master/README.md

But it sounds like you already got that covered. Just for a test have you tried first saving the file than executing it via `Run > Execute Document in Maya`? and let me know if that yields the same result.

It sounds like the issue is the temp files MayaCharm uses to communicate with Maya are not being written, or they are not accessible by Maya. To test this, can you try and use MayaCharm to run a file a few times, and without shutting down PyCharm can you check your user's Temp directory `%TEMP%` and look for any files Prefixed with `MayaCharmTemp` and confirm that these files are actually being created.

Also it would be much easier for me if further communication is done via either my email address chris@rightsomegoodgames.ca or via the issues page on my github.

**Comment by cmcpasserby** [comment] 2017-04-03 02:57
closing un till i get data

**Closed by cmcpasserby** 2017-04-03 02:57 UTC

**Comment by IonutStef** [comment] 2017-04-03 08:48
Hei..

...It's been so long.. I'm really sorry for not contacting you back
earlier! I always thought that I've already closed this topic.

Yes, with Run > Execute Document in Maya it worked without problems. I
don't know why I've thought that it should have worked with simple run, as
well.

Thank you very much for your help!
And again, I'm really sorry for not saying anything.. I hope I haven't
troubled you too much with it...

Stefan
